apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-anonymous-api-access
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin  # or more restricted role
subjects:
- kind: User
  name: system:anonymous
