apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin-secret
  namespace: jenkins
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
  jenkins-user: YWRtaW4=         # base64 for 'admin'
  jenkins-password: YWRtaW4xMjM= # base64 for 'admin123'
