apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-proxy-headers
  namespace: jenkins
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  X-Forwarded-Proto: "https"
  X-Forwarded-Port: "443"
  X-Forwarded-Host: "$host"
  X-Forwarded-For: "$proxy_add_x_forwarded_for"
  X-Real-IP: "$remote_addr"
