apiVersion: v1
kind: Secret
metadata:
  name: jenkins-sa-token
  namespace: jenkins
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: jenkins
  annotations:
    kubernetes.io/service-account.name: jenkins
    argocd.argoproj.io/sync-wave: "-1"
type: kubernetes.io/service-account-token
